package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for createExtended3DField kernel
var createExtended3DField_code cu.Function

// Stores the arguments for createExtended3DField kernel invocation
type createExtended3DField_args_t struct {
	arg_uxExt unsafe.Pointer
	arg_uyExt unsafe.Pointer
	arg_uzExt unsafe.Pointer
	arg_ux    unsafe.Pointer
	arg_uy    unsafe.Pointer
	arg_uz    unsafe.Pointer
	arg_Nx    int
	arg_Ny    int
	arg_Nz    int
	arg_PBC   byte
	argptr    [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for createExtended3DField kernel invocation
var createExtended3DField_args createExtended3DField_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	createExtended3DField_args.argptr[0] = unsafe.Pointer(&createExtended3DField_args.arg_uxExt)
	createExtended3DField_args.argptr[1] = unsafe.Pointer(&createExtended3DField_args.arg_uyExt)
	createExtended3DField_args.argptr[2] = unsafe.Pointer(&createExtended3DField_args.arg_uzExt)
	createExtended3DField_args.argptr[3] = unsafe.Pointer(&createExtended3DField_args.arg_ux)
	createExtended3DField_args.argptr[4] = unsafe.Pointer(&createExtended3DField_args.arg_uy)
	createExtended3DField_args.argptr[5] = unsafe.Pointer(&createExtended3DField_args.arg_uz)
	createExtended3DField_args.argptr[6] = unsafe.Pointer(&createExtended3DField_args.arg_Nx)
	createExtended3DField_args.argptr[7] = unsafe.Pointer(&createExtended3DField_args.arg_Ny)
	createExtended3DField_args.argptr[8] = unsafe.Pointer(&createExtended3DField_args.arg_Nz)
	createExtended3DField_args.argptr[9] = unsafe.Pointer(&createExtended3DField_args.arg_PBC)
}

// Wrapper for createExtended3DField CUDA kernel, asynchronous.
func k_createExtended3DField_async(uxExt unsafe.Pointer, uyExt unsafe.Pointer, uzExt unsafe.Pointer, ux unsafe.Pointer, uy unsafe.Pointer, uz unsafe.Pointer, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("createExtended3DField")
	}

	createExtended3DField_args.Lock()
	defer createExtended3DField_args.Unlock()

	if createExtended3DField_code == 0 {
		createExtended3DField_code = fatbinLoad(createExtended3DField_map, "createExtended3DField")
	}

	createExtended3DField_args.arg_uxExt = uxExt
	createExtended3DField_args.arg_uyExt = uyExt
	createExtended3DField_args.arg_uzExt = uzExt
	createExtended3DField_args.arg_ux = ux
	createExtended3DField_args.arg_uy = uy
	createExtended3DField_args.arg_uz = uz
	createExtended3DField_args.arg_Nx = Nx
	createExtended3DField_args.arg_Ny = Ny
	createExtended3DField_args.arg_Nz = Nz
	createExtended3DField_args.arg_PBC = PBC

	args := createExtended3DField_args.argptr[:]
	cu.LaunchKernel(createExtended3DField_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("createExtended3DField")
	}
}

// maps compute capability on PTX code for createExtended3DField kernel.
var createExtended3DField_map = map[int]string{0: "",
	50: createExtended3DField_ptx_50,
	52: createExtended3DField_ptx_52,
	53: createExtended3DField_ptx_53,
	60: createExtended3DField_ptx_60,
	61: createExtended3DField_ptx_61,
	62: createExtended3DField_ptx_62,
	70: createExtended3DField_ptx_70}

// createExtended3DField PTX code for various compute capabilities.
const (
	createExtended3DField_ptx_50 = `
.version 8.4
.target sm_50
.address_size 64

	// .globl	createExtended3DField

.visible .entry createExtended3DField(
	.param .u64 createExtended3DField_param_0,
	.param .u64 createExtended3DField_param_1,
	.param .u64 createExtended3DField_param_2,
	.param .u64 createExtended3DField_param_3,
	.param .u64 createExtended3DField_param_4,
	.param .u64 createExtended3DField_param_5,
	.param .u32 createExtended3DField_param_6,
	.param .u32 createExtended3DField_param_7,
	.param .u32 createExtended3DField_param_8,
	.param .u8 createExtended3DField_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [createExtended3DField_param_0];
	ld.param.u8 	%rs4, [createExtended3DField_param_9];
	ld.param.u64 	%rd2, [createExtended3DField_param_1];
	ld.param.u64 	%rd3, [createExtended3DField_param_2];
	ld.param.u64 	%rd4, [createExtended3DField_param_3];
	ld.param.u64 	%rd5, [createExtended3DField_param_4];
	ld.param.u64 	%rd6, [createExtended3DField_param_5];
	ld.param.u32 	%r6, [createExtended3DField_param_6];
	ld.param.u32 	%r7, [createExtended3DField_param_7];
	ld.param.u32 	%r8, [createExtended3DField_param_8];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd8, %r38, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r40, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd2;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd3;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
	createExtended3DField_ptx_52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	createExtended3DField

.visible .entry createExtended3DField(
	.param .u64 createExtended3DField_param_0,
	.param .u64 createExtended3DField_param_1,
	.param .u64 createExtended3DField_param_2,
	.param .u64 createExtended3DField_param_3,
	.param .u64 createExtended3DField_param_4,
	.param .u64 createExtended3DField_param_5,
	.param .u32 createExtended3DField_param_6,
	.param .u32 createExtended3DField_param_7,
	.param .u32 createExtended3DField_param_8,
	.param .u8 createExtended3DField_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [createExtended3DField_param_0];
	ld.param.u8 	%rs4, [createExtended3DField_param_9];
	ld.param.u64 	%rd2, [createExtended3DField_param_1];
	ld.param.u64 	%rd3, [createExtended3DField_param_2];
	ld.param.u64 	%rd4, [createExtended3DField_param_3];
	ld.param.u64 	%rd5, [createExtended3DField_param_4];
	ld.param.u64 	%rd6, [createExtended3DField_param_5];
	ld.param.u32 	%r6, [createExtended3DField_param_6];
	ld.param.u32 	%r7, [createExtended3DField_param_7];
	ld.param.u32 	%r8, [createExtended3DField_param_8];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd8, %r38, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r40, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd2;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd3;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
	createExtended3DField_ptx_53 = `
.version 8.4
.target sm_53
.address_size 64

	// .globl	createExtended3DField

.visible .entry createExtended3DField(
	.param .u64 createExtended3DField_param_0,
	.param .u64 createExtended3DField_param_1,
	.param .u64 createExtended3DField_param_2,
	.param .u64 createExtended3DField_param_3,
	.param .u64 createExtended3DField_param_4,
	.param .u64 createExtended3DField_param_5,
	.param .u32 createExtended3DField_param_6,
	.param .u32 createExtended3DField_param_7,
	.param .u32 createExtended3DField_param_8,
	.param .u8 createExtended3DField_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [createExtended3DField_param_0];
	ld.param.u8 	%rs4, [createExtended3DField_param_9];
	ld.param.u64 	%rd2, [createExtended3DField_param_1];
	ld.param.u64 	%rd3, [createExtended3DField_param_2];
	ld.param.u64 	%rd4, [createExtended3DField_param_3];
	ld.param.u64 	%rd5, [createExtended3DField_param_4];
	ld.param.u64 	%rd6, [createExtended3DField_param_5];
	ld.param.u32 	%r6, [createExtended3DField_param_6];
	ld.param.u32 	%r7, [createExtended3DField_param_7];
	ld.param.u32 	%r8, [createExtended3DField_param_8];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd8, %r38, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r40, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd2;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd3;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
	createExtended3DField_ptx_60 = `
.version 8.4
.target sm_60
.address_size 64

	// .globl	createExtended3DField

.visible .entry createExtended3DField(
	.param .u64 createExtended3DField_param_0,
	.param .u64 createExtended3DField_param_1,
	.param .u64 createExtended3DField_param_2,
	.param .u64 createExtended3DField_param_3,
	.param .u64 createExtended3DField_param_4,
	.param .u64 createExtended3DField_param_5,
	.param .u32 createExtended3DField_param_6,
	.param .u32 createExtended3DField_param_7,
	.param .u32 createExtended3DField_param_8,
	.param .u8 createExtended3DField_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [createExtended3DField_param_0];
	ld.param.u8 	%rs4, [createExtended3DField_param_9];
	ld.param.u64 	%rd2, [createExtended3DField_param_1];
	ld.param.u64 	%rd3, [createExtended3DField_param_2];
	ld.param.u64 	%rd4, [createExtended3DField_param_3];
	ld.param.u64 	%rd5, [createExtended3DField_param_4];
	ld.param.u64 	%rd6, [createExtended3DField_param_5];
	ld.param.u32 	%r6, [createExtended3DField_param_6];
	ld.param.u32 	%r7, [createExtended3DField_param_7];
	ld.param.u32 	%r8, [createExtended3DField_param_8];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd8, %r38, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r40, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd2;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd3;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
	createExtended3DField_ptx_61 = `
.version 8.4
.target sm_61
.address_size 64

	// .globl	createExtended3DField

.visible .entry createExtended3DField(
	.param .u64 createExtended3DField_param_0,
	.param .u64 createExtended3DField_param_1,
	.param .u64 createExtended3DField_param_2,
	.param .u64 createExtended3DField_param_3,
	.param .u64 createExtended3DField_param_4,
	.param .u64 createExtended3DField_param_5,
	.param .u32 createExtended3DField_param_6,
	.param .u32 createExtended3DField_param_7,
	.param .u32 createExtended3DField_param_8,
	.param .u8 createExtended3DField_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [createExtended3DField_param_0];
	ld.param.u8 	%rs4, [createExtended3DField_param_9];
	ld.param.u64 	%rd2, [createExtended3DField_param_1];
	ld.param.u64 	%rd3, [createExtended3DField_param_2];
	ld.param.u64 	%rd4, [createExtended3DField_param_3];
	ld.param.u64 	%rd5, [createExtended3DField_param_4];
	ld.param.u64 	%rd6, [createExtended3DField_param_5];
	ld.param.u32 	%r6, [createExtended3DField_param_6];
	ld.param.u32 	%r7, [createExtended3DField_param_7];
	ld.param.u32 	%r8, [createExtended3DField_param_8];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd8, %r38, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r40, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd2;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd3;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
	createExtended3DField_ptx_62 = `
.version 8.4
.target sm_62
.address_size 64

	// .globl	createExtended3DField

.visible .entry createExtended3DField(
	.param .u64 createExtended3DField_param_0,
	.param .u64 createExtended3DField_param_1,
	.param .u64 createExtended3DField_param_2,
	.param .u64 createExtended3DField_param_3,
	.param .u64 createExtended3DField_param_4,
	.param .u64 createExtended3DField_param_5,
	.param .u32 createExtended3DField_param_6,
	.param .u32 createExtended3DField_param_7,
	.param .u32 createExtended3DField_param_8,
	.param .u8 createExtended3DField_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [createExtended3DField_param_0];
	ld.param.u8 	%rs4, [createExtended3DField_param_9];
	ld.param.u64 	%rd2, [createExtended3DField_param_1];
	ld.param.u64 	%rd3, [createExtended3DField_param_2];
	ld.param.u64 	%rd4, [createExtended3DField_param_3];
	ld.param.u64 	%rd5, [createExtended3DField_param_4];
	ld.param.u64 	%rd6, [createExtended3DField_param_5];
	ld.param.u32 	%r6, [createExtended3DField_param_6];
	ld.param.u32 	%r7, [createExtended3DField_param_7];
	ld.param.u32 	%r8, [createExtended3DField_param_8];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd8, %r38, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r40, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd2;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd3;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
	createExtended3DField_ptx_70 = `
.version 8.4
.target sm_70
.address_size 64

	// .globl	createExtended3DField

.visible .entry createExtended3DField(
	.param .u64 createExtended3DField_param_0,
	.param .u64 createExtended3DField_param_1,
	.param .u64 createExtended3DField_param_2,
	.param .u64 createExtended3DField_param_3,
	.param .u64 createExtended3DField_param_4,
	.param .u64 createExtended3DField_param_5,
	.param .u32 createExtended3DField_param_6,
	.param .u32 createExtended3DField_param_7,
	.param .u32 createExtended3DField_param_8,
	.param .u8 createExtended3DField_param_9
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<21>;


	ld.param.u64 	%rd1, [createExtended3DField_param_0];
	ld.param.u8 	%rs4, [createExtended3DField_param_9];
	ld.param.u64 	%rd2, [createExtended3DField_param_1];
	ld.param.u64 	%rd3, [createExtended3DField_param_2];
	ld.param.u64 	%rd4, [createExtended3DField_param_3];
	ld.param.u64 	%rd5, [createExtended3DField_param_4];
	ld.param.u64 	%rd6, [createExtended3DField_param_5];
	ld.param.u32 	%r6, [createExtended3DField_param_6];
	ld.param.u32 	%r7, [createExtended3DField_param_7];
	ld.param.u32 	%r8, [createExtended3DField_param_8];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd8, %r38, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f1, [%rd9];
	cvta.to.global.u64 	%rd10, %rd1;
	mul.wide.s32 	%rd11, %r40, 4;
	add.s64 	%rd12, %rd10, %rd11;
	st.global.f32 	[%rd12], %f1;
	cvta.to.global.u64 	%rd13, %rd5;
	add.s64 	%rd14, %rd13, %rd8;
	ld.global.nc.f32 	%f2, [%rd14];
	cvta.to.global.u64 	%rd15, %rd2;
	add.s64 	%rd16, %rd15, %rd11;
	st.global.f32 	[%rd16], %f2;
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd8;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd3;
	add.s64 	%rd20, %rd19, %rd11;
	st.global.f32 	[%rd20], %f3;

$L__BB0_2:
	ret;

}

`
)
