package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for extendParameterField kernel
var extendParameterField_code cu.Function

// Stores the arguments for extendParameterField kernel invocation
type extendParameterField_args_t struct {
	arg_paramsExt unsafe.Pointer
	arg_params    unsafe.Pointer
	arg_Nx        int
	arg_Ny        int
	arg_Nz        int
	arg_PBC       byte
	argptr        [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for extendParameterField kernel invocation
var extendParameterField_args extendParameterField_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	extendParameterField_args.argptr[0] = unsafe.Pointer(&extendParameterField_args.arg_paramsExt)
	extendParameterField_args.argptr[1] = unsafe.Pointer(&extendParameterField_args.arg_params)
	extendParameterField_args.argptr[2] = unsafe.Pointer(&extendParameterField_args.arg_Nx)
	extendParameterField_args.argptr[3] = unsafe.Pointer(&extendParameterField_args.arg_Ny)
	extendParameterField_args.argptr[4] = unsafe.Pointer(&extendParameterField_args.arg_Nz)
	extendParameterField_args.argptr[5] = unsafe.Pointer(&extendParameterField_args.arg_PBC)
}

// Wrapper for extendParameterField CUDA kernel, asynchronous.
func k_extendParameterField_async(paramsExt unsafe.Pointer, params unsafe.Pointer, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("extendParameterField")
	}

	extendParameterField_args.Lock()
	defer extendParameterField_args.Unlock()

	if extendParameterField_code == 0 {
		extendParameterField_code = fatbinLoad(extendParameterField_map, "extendParameterField")
	}

	extendParameterField_args.arg_paramsExt = paramsExt
	extendParameterField_args.arg_params = params
	extendParameterField_args.arg_Nx = Nx
	extendParameterField_args.arg_Ny = Ny
	extendParameterField_args.arg_Nz = Nz
	extendParameterField_args.arg_PBC = PBC

	args := extendParameterField_args.argptr[:]
	cu.LaunchKernel(extendParameterField_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("extendParameterField")
	}
}

// maps compute capability on PTX code for extendParameterField kernel.
var extendParameterField_map = map[int]string{0: "",
	50: extendParameterField_ptx_50,
	52: extendParameterField_ptx_52,
	53: extendParameterField_ptx_53,
	60: extendParameterField_ptx_60,
	61: extendParameterField_ptx_61,
	62: extendParameterField_ptx_62,
	70: extendParameterField_ptx_70}

// extendParameterField PTX code for various compute capabilities.
const (
	extendParameterField_ptx_50 = `
.version 8.5
.target sm_50
.address_size 64

	// .globl	extendParameterField

.visible .entry extendParameterField(
	.param .u64 extendParameterField_param_0,
	.param .u64 extendParameterField_param_1,
	.param .u32 extendParameterField_param_2,
	.param .u32 extendParameterField_param_3,
	.param .u32 extendParameterField_param_4,
	.param .u8 extendParameterField_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [extendParameterField_param_0];
	ld.param.u8 	%rs4, [extendParameterField_param_5];
	ld.param.u64 	%rd2, [extendParameterField_param_1];
	ld.param.u32 	%r6, [extendParameterField_param_2];
	ld.param.u32 	%r7, [extendParameterField_param_3];
	ld.param.u32 	%r8, [extendParameterField_param_4];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd4, %r38, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f1;

$L__BB0_2:
	ret;

}

`
	extendParameterField_ptx_52 = `
.version 8.5
.target sm_52
.address_size 64

	// .globl	extendParameterField

.visible .entry extendParameterField(
	.param .u64 extendParameterField_param_0,
	.param .u64 extendParameterField_param_1,
	.param .u32 extendParameterField_param_2,
	.param .u32 extendParameterField_param_3,
	.param .u32 extendParameterField_param_4,
	.param .u8 extendParameterField_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [extendParameterField_param_0];
	ld.param.u8 	%rs4, [extendParameterField_param_5];
	ld.param.u64 	%rd2, [extendParameterField_param_1];
	ld.param.u32 	%r6, [extendParameterField_param_2];
	ld.param.u32 	%r7, [extendParameterField_param_3];
	ld.param.u32 	%r8, [extendParameterField_param_4];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd4, %r38, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f1;

$L__BB0_2:
	ret;

}

`
	extendParameterField_ptx_53 = `
.version 8.5
.target sm_53
.address_size 64

	// .globl	extendParameterField

.visible .entry extendParameterField(
	.param .u64 extendParameterField_param_0,
	.param .u64 extendParameterField_param_1,
	.param .u32 extendParameterField_param_2,
	.param .u32 extendParameterField_param_3,
	.param .u32 extendParameterField_param_4,
	.param .u8 extendParameterField_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [extendParameterField_param_0];
	ld.param.u8 	%rs4, [extendParameterField_param_5];
	ld.param.u64 	%rd2, [extendParameterField_param_1];
	ld.param.u32 	%r6, [extendParameterField_param_2];
	ld.param.u32 	%r7, [extendParameterField_param_3];
	ld.param.u32 	%r8, [extendParameterField_param_4];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd4, %r38, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f1;

$L__BB0_2:
	ret;

}

`
	extendParameterField_ptx_60 = `
.version 8.5
.target sm_60
.address_size 64

	// .globl	extendParameterField

.visible .entry extendParameterField(
	.param .u64 extendParameterField_param_0,
	.param .u64 extendParameterField_param_1,
	.param .u32 extendParameterField_param_2,
	.param .u32 extendParameterField_param_3,
	.param .u32 extendParameterField_param_4,
	.param .u8 extendParameterField_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [extendParameterField_param_0];
	ld.param.u8 	%rs4, [extendParameterField_param_5];
	ld.param.u64 	%rd2, [extendParameterField_param_1];
	ld.param.u32 	%r6, [extendParameterField_param_2];
	ld.param.u32 	%r7, [extendParameterField_param_3];
	ld.param.u32 	%r8, [extendParameterField_param_4];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd4, %r38, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f1;

$L__BB0_2:
	ret;

}

`
	extendParameterField_ptx_61 = `
.version 8.5
.target sm_61
.address_size 64

	// .globl	extendParameterField

.visible .entry extendParameterField(
	.param .u64 extendParameterField_param_0,
	.param .u64 extendParameterField_param_1,
	.param .u32 extendParameterField_param_2,
	.param .u32 extendParameterField_param_3,
	.param .u32 extendParameterField_param_4,
	.param .u8 extendParameterField_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [extendParameterField_param_0];
	ld.param.u8 	%rs4, [extendParameterField_param_5];
	ld.param.u64 	%rd2, [extendParameterField_param_1];
	ld.param.u32 	%r6, [extendParameterField_param_2];
	ld.param.u32 	%r7, [extendParameterField_param_3];
	ld.param.u32 	%r8, [extendParameterField_param_4];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd4, %r38, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f1;

$L__BB0_2:
	ret;

}

`
	extendParameterField_ptx_62 = `
.version 8.5
.target sm_62
.address_size 64

	// .globl	extendParameterField

.visible .entry extendParameterField(
	.param .u64 extendParameterField_param_0,
	.param .u64 extendParameterField_param_1,
	.param .u32 extendParameterField_param_2,
	.param .u32 extendParameterField_param_3,
	.param .u32 extendParameterField_param_4,
	.param .u8 extendParameterField_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [extendParameterField_param_0];
	ld.param.u8 	%rs4, [extendParameterField_param_5];
	ld.param.u64 	%rd2, [extendParameterField_param_1];
	ld.param.u32 	%r6, [extendParameterField_param_2];
	ld.param.u32 	%r7, [extendParameterField_param_3];
	ld.param.u32 	%r8, [extendParameterField_param_4];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd4, %r38, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f1;

$L__BB0_2:
	ret;

}

`
	extendParameterField_ptx_70 = `
.version 8.5
.target sm_70
.address_size 64

	// .globl	extendParameterField

.visible .entry extendParameterField(
	.param .u64 extendParameterField_param_0,
	.param .u64 extendParameterField_param_1,
	.param .u32 extendParameterField_param_2,
	.param .u32 extendParameterField_param_3,
	.param .u32 extendParameterField_param_4,
	.param .u8 extendParameterField_param_5
)
{
	.reg .pred 	%p<12>;
	.reg .b16 	%rs<11>;
	.reg .f32 	%f<2>;
	.reg .b32 	%r<41>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [extendParameterField_param_0];
	ld.param.u8 	%rs4, [extendParameterField_param_5];
	ld.param.u64 	%rd2, [extendParameterField_param_1];
	ld.param.u32 	%r6, [extendParameterField_param_2];
	ld.param.u32 	%r7, [extendParameterField_param_3];
	ld.param.u32 	%r8, [extendParameterField_param_4];
	and.b16  	%rs1, %rs4, 1;
	shl.b16 	%rs5, %rs4, 1;
	not.b16 	%rs6, %rs5;
	and.b16  	%rs7, %rs6, 2;
	cvt.u32.u16 	%r9, %rs7;
	add.s32 	%r1, %r9, %r6;
	and.b16  	%rs2, %rs4, 2;
	xor.b16  	%rs8, %rs2, 2;
	cvt.u32.u16 	%r10, %rs8;
	add.s32 	%r2, %r10, %r7;
	and.b16  	%rs3, %rs4, 4;
	shr.u16 	%rs9, %rs3, 1;
	xor.b16  	%rs10, %rs9, 2;
	cvt.u32.u16 	%r11, %rs10;
	add.s32 	%r12, %r11, %r8;
	mov.u32 	%r13, %ntid.x;
	mov.u32 	%r14, %ctaid.x;
	mov.u32 	%r15, %tid.x;
	mad.lo.s32 	%r3, %r14, %r13, %r15;
	mov.u32 	%r16, %ntid.y;
	mov.u32 	%r17, %ctaid.y;
	mov.u32 	%r18, %tid.y;
	mad.lo.s32 	%r4, %r17, %r16, %r18;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %ctaid.z;
	mov.u32 	%r21, %tid.z;
	mad.lo.s32 	%r5, %r20, %r19, %r21;
	setp.ge.s32 	%p1, %r3, %r1;
	setp.ge.s32 	%p2, %r4, %r2;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32 	%p4, %r5, %r12;
	or.pred  	%p5, %p4, %p3;
	@%p5 bra 	$L__BB0_2;

	cvta.to.global.u64 	%rd3, %rd2;
	setp.eq.s16 	%p6, %rs1, 0;
	selp.b32 	%r22, -1, 0, %p6;
	add.s32 	%r23, %r3, %r22;
	max.s32 	%r24, %r23, 0;
	setp.lt.s32 	%p7, %r24, %r6;
	add.s32 	%r25, %r6, -1;
	selp.b32 	%r26, %r24, %r25, %p7;
	setp.eq.s16 	%p8, %rs2, 0;
	selp.b32 	%r27, -1, 0, %p8;
	add.s32 	%r28, %r4, %r27;
	max.s32 	%r29, %r28, 0;
	setp.lt.s32 	%p9, %r29, %r7;
	add.s32 	%r30, %r7, -1;
	selp.b32 	%r31, %r29, %r30, %p9;
	setp.eq.s16 	%p10, %rs3, 0;
	selp.b32 	%r32, -1, 0, %p10;
	add.s32 	%r33, %r5, %r32;
	max.s32 	%r34, %r33, 0;
	setp.lt.s32 	%p11, %r34, %r8;
	add.s32 	%r35, %r8, -1;
	selp.b32 	%r36, %r34, %r35, %p11;
	mad.lo.s32 	%r37, %r36, %r7, %r31;
	mad.lo.s32 	%r38, %r37, %r6, %r26;
	mad.lo.s32 	%r39, %r2, %r5, %r4;
	mad.lo.s32 	%r40, %r39, %r1, %r3;
	mul.wide.s32 	%rd4, %r38, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r40, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f1;

$L__BB0_2:
	ret;

}

`
)
